/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './index.html',
    './src/**/*.{ts,tsx,js,jsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    screens: {
      'xs': '475px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      'tablet': '768px',
      'laptop': '1024px',
      'desktop': '1280px',
      'mobile-only': { 'max': '767px' },
      'tablet-only': { 'min': '768px', 'max': '1023px' },
      'desktop-only': { 'min': '1024px' },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontSize: {
        'xs-mobile': ['0.65rem', { lineHeight: '1rem' }],
        'sm-mobile': ['0.75rem', { lineHeight: '1.25rem' }],
        'base-mobile': ['0.85rem', { lineHeight: '1.5rem' }],
        'lg-mobile': ['0.95rem', { lineHeight: '1.75rem' }],
        'xl-mobile': ['1.05rem', { lineHeight: '1.75rem' }],
        'xs-tablet': ['0.7rem', { lineHeight: '1rem' }],
        'sm-tablet': ['0.8rem', { lineHeight: '1.25rem' }],
        'base-tablet': ['0.9rem', { lineHeight: '1.5rem' }],
        'lg-tablet': ['1rem', { lineHeight: '1.75rem' }],
        'xl-tablet': ['1.125rem', { lineHeight: '1.75rem' }],
      },
      spacing: {
        'responsive-1': 'var(--spacing-1)',
        'responsive-2': 'var(--spacing-2)',
        'responsive-3': 'var(--spacing-3)',
        'responsive-4': 'var(--spacing-4)',
        'responsive-6': 'var(--spacing-6)',
        'responsive-8': 'var(--spacing-8)',
        'mobile-1': '0.2rem',
        'mobile-2': '0.4rem',
        'mobile-3': '0.6rem',
        'mobile-4': '0.8rem',
        'mobile-6': '1.2rem',
        'mobile-8': '1.6rem',
        'tablet-1': '0.25rem',
        'tablet-2': '0.5rem',
        'tablet-3': '0.75rem',
        'tablet-4': '1rem',
        'tablet-6': '1.5rem',
        'tablet-8': '2rem',
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "fade-in": {
          "0%": { opacity: 0 },
          "100%": { opacity: 1 },
        },
        "slide-up": {
          "0%": { opacity: 0, transform: "translateY(8px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        "slide-down": {
          "0%": { opacity: 0, transform: "translateY(-8px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: 0, transform: "scale(0.95)" },
          "100%": { opacity: 1, transform: "scale(1)" },
        },
        "pulse-subtle": {
          "0%, 100%": { opacity: 1 },
          "50%": { opacity: 0.7 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "slide-up": "slide-up 0.25s ease-out",
        "slide-down": "slide-down 0.25s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        "pulse-subtle": "pulse-subtle 2s ease-in-out infinite",
      },
      boxShadow: {
        'minimal': 'var(--shadow-minimal)',
        'subtle': 'var(--shadow-subtle)',
        'moderate': 'var(--shadow-moderate)',
        'strong': 'var(--shadow-strong)',
        'mobile-sm': '0 1px 2px rgba(0, 0, 0, 0.05)',
        'mobile': '0 2px 4px rgba(0, 0, 0, 0.06)',
        'mobile-md': '0 4px 6px rgba(0, 0, 0, 0.07)',
        'tablet-sm': '0 1px 3px rgba(0, 0, 0, 0.06)',
        'tablet': '0 4px 6px rgba(0, 0, 0, 0.05), 0 1px 3px rgba(0, 0, 0, 0.08)',
        'tablet-md': '0 6px 8px rgba(0, 0, 0, 0.06)',
      },
      maxWidth: {
        'mobile': '100vw',
        'tablet': '768px',
        'laptop': '1024px',
        'desktop': '1280px',
        'chat-mobile': '95vw',
        'chat-tablet': '85vw',
        'chat-desktop': '80vw',
      },
      minHeight: {
        'mobile-screen': '100vh',
        'tablet-screen': '100vh',
        'chat-input': '32px',
        'chat-input-tablet': '44px',
        'chat-input-desktop': '52px',
      },
      zIndex: {
        'dropdown': '50',
        'modal': '100',
        'toast': '200',
        'tooltip': '300',
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
  ],
}
